apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  selector:
    app: storage-server
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
      nodePort: 30001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: storage-server
  template:
    metadata:
      labels:
        app: storage-server
    spec:
      containers:
      - name: storage-container
        image: storage-server:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 12345
        env:
        - name: K8S_SERVICE_HOST
          value: "storage-service"
        - name: K8S_SERVICE_PORT
          value: "12345"